Algoritmo "semnome"

        
Var
 emprestimo,parcelas,total: real


Inicio

      escreval("valor do emprestimo: ")
      leia(emprestimo)
      emprestimo <- (emprestimo  * 20) / 100 + emprestimo
      escreval("devolvera o valor total de: ", emprestimo)
      escreval("valor das parcelas: ")
      leia(parcelas)
      total <- emprestimo / parcelas
      escreval("valor de cada parcela sera de: ",total)





    escreval


Fimalgoritmo