algoritmo "Contador Inteligente"
var
     ini,fim,contador:inteiro
inicio
    escreva("inicio: ")
    leia(ini)
    escreva("fim: ")
    leia(fim)
    
    contador <- ini
    
    Se( ini <= fim)entao
     enquanto (contador <= fim)faca
              escreva(contador,"..")
              contador <- contador + 1
     fimenquanto
    Senao
     enquanto (contador >= fim)faca
      escreva(contador,"..")
      contador <- contador - 1
      fimenquanto
      fimse
    




fimalgoritmo